"""Init

Revision ID: 35c6bd819b9f
Revises: 
Create Date: 2023-07-07 11:43:10.087151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c6bd819b9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_directions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_code', sa.String(length=3), nullable=False),
    sa.Column('start_name', sa.Text(), nullable=False),
    sa.Column('end_code', sa.String(length=3), nullable=False),
    sa.Column('end_name', sa.Text(), nullable=False),
    sa.Column('with_transfer', sa.Boolean(), nullable=False),
    sa.Column('departure_at', sa.String(length=10), nullable=False),
    sa.Column('return_at', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_code', 'end_code', 'with_transfer', 'departure_at', 'return_at', name='flight_directions_uc')
    )
    op.create_table('historic_flight_directions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_code', sa.String(length=3), nullable=False),
    sa.Column('start_name', sa.Text(), nullable=False),
    sa.Column('end_code', sa.String(length=3), nullable=False),
    sa.Column('end_name', sa.Text(), nullable=False),
    sa.Column('with_transfer', sa.Boolean(), nullable=False),
    sa.Column('departure_at', sa.String(length=10), nullable=False),
    sa.Column('return_at', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_by_user', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('departure_at', sa.DateTime(), nullable=False),
    sa.Column('duration_to', sa.Integer(), nullable=False),
    sa.Column('return_at', sa.DateTime(), nullable=True),
    sa.Column('duration_back', sa.Integer(), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['flight_directions.id'], name='tickets_fk__flight_direction', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_directions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['flight_directions.id'], name='users_directions_fk__flight_direction', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'direction_id', name='users_directions_pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_directions')
    op.drop_table('tickets')
    op.drop_table('users')
    op.drop_table('historic_flight_directions')
    op.drop_table('flight_directions')
    # ### end Alembic commands ###
