"""Add tickets

Revision ID: 79ef2c9e4933
Revises: 81984bb2b857
Create Date: 2023-06-23 23:38:04.892220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ef2c9e4933'
down_revision = '81984bb2b857'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('departure_at', sa.DateTime(), nullable=False),
    sa.Column('duration_to', sa.Integer(), nullable=False),
    sa.Column('return_at', sa.DateTime(), nullable=True),
    sa.Column('duration_back', sa.DateTime(), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['flight_direction.id'], name='tickets_fk__flight_direction', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
